const pptxgen=require('pptxgenjs');
const pptx=new pptxgen();pptx.layout='LAYOUT_WIDE';pptx.author='RelayMesh';pptx.subject='3rd Web Hack submission';pptx.title='RelayMesh — Messages find a way';pptx.company='RelayMesh';pptx.lang='en-US';
pptx.theme={headFontFace:'Aptos Display',bodyFontFace:'Aptos',lang:'en-US'};
const C={ink:'0B1714',green:'006B4B',lime:'B9F35A',paper:'F5F3E9',muted:'66736F',white:'FFFFFF',line:'D9DED7'};
const hero='../assets/relaymesh-thumbnail.png',screen='../assets/relaymesh-demo.png';
function base(title,kicker){const s=pptx.addSlide();s.background={color:C.paper};s.addText(kicker.toUpperCase(),{x:.72,y:.45,w:5,h:.24,fontSize:10,bold:true,color:C.green,charSpacing:2});s.addText(title,{x:.7,y:.82,w:11.9,h:.7,fontSize:31,bold:true,color:C.ink,margin:0});s.addShape(pptx.ShapeType.line,{x:.7,y:1.62,w:11.9,h:0,line:{color:C.line,width:1}});return s}
function footer(s,n){s.addText(`RELAYMESH  /  3RD WEB HACK`,{x:.7,y:7.18,w:4,h:.16,fontSize:8,bold:true,color:C.muted});s.addText(String(n).padStart(2,'0'),{x:12,y:7.14,w:.55,h:.18,fontSize:9,bold:true,color:C.green,align:'right'})}
let s=pptx.addSlide();s.background={color:C.ink};s.addImage({path:hero,x:6.3,y:0,w:7.04,h:7.5});s.addShape(pptx.ShapeType.rect,{x:0,y:0,w:7.2,h:7.5,fill:{color:C.ink,transparency:0},line:{transparency:100}});s.addText('DECENTRALIZED DELAY-TOLERANT MESSAGING',{x:.75,y:.7,w:5.8,h:.3,fontSize:10,bold:true,color:C.lime,charSpacing:2});s.addText('RelayMesh',{x:.72,y:1.45,w:5.8,h:.7,fontSize:43,bold:true,color:C.white,margin:0});s.addText('Messages find a way.\nEven when networks fail.',{x:.75,y:2.35,w:5.25,h:1.55,fontSize:30,bold:true,color:C.white,breakLine:false,margin:0});s.addText('Encrypted fragments travel across opt-in devices. Useful relays earn RLY only after delivery.',{x:.76,y:4.35,w:4.85,h:1,fontSize:16,color:'C6D2CE',breakLine:false,margin:0});s.addText('WORKING MVP  •  SOLIDITY  •  WEB CRYPTO',{x:.76,y:6.55,w:5.2,h:.28,fontSize:10,bold:true,color:C.lime,charSpacing:1.3});footer(s,1);
s=base('Networks fail exactly when communication matters most.','The problem');s.addText('Centralized messaging has three brittle dependencies:',{x:.75,y:1.95,w:5.5,h:.45,fontSize:20,bold:true,color:C.ink});const problems=[['01','A live route','No cellular or internet path means no delivery.'],['02','A trusted platform','A single provider can fail, censor, or disappear.'],['03','Free relay labor','Strangers have no reason to carry encrypted traffic.']];problems.forEach((p,i)=>{const y=2.65+i*1.13;s.addText(p[0],{x:.78,y,w:.5,h:.3,fontSize:11,bold:true,color:C.green});s.addText(p[1],{x:1.42,y:y-.02,w:2.2,h:.3,fontSize:16,bold:true,color:C.ink});s.addText(p[2],{x:3.7,y:y-.02,w:7.9,h:.42,fontSize:14,color:C.muted});});s.addText('RelayMesh removes all three.',{x:.78,y:6.25,w:5,h:.45,fontSize:25,bold:true,color:C.green});footer(s,2);
s=base('Encrypt → fragment → relay → reconstruct → reward','How it works');const steps=[['1','Encrypt locally','AES-256-GCM; plaintext never reaches a relay.'],['2','Scatter fragments','Shuffled ciphertext takes independent store-carry-forward paths.'],['3','Find the receiver','Phrase-derived rotating tags avoid a permanent public identity.'],['4','Settle useful work','Receiver-signed receipt releases escrowed RLY.']];steps.forEach((p,i)=>{const x=.75+i*3.03;s.addShape(pptx.ShapeType.roundRect,{x,y:2.05,w:2.55,h:3.55,rectRadius:.08,fill:{color:i===3?C.ink:C.white},line:{color:i===3?C.ink:C.line,width:1}});s.addText(p[0],{x:x+.22,y:2.3,w:.48,h:.48,fontSize:20,bold:true,color:i===3?C.lime:C.green,align:'center',valign:'mid'});s.addText(p[1],{x:x+.22,y:3.05,w:2.05,h:.72,fontSize:19,bold:true,color:i===3?C.white:C.ink,margin:0});s.addText(p[2],{x:x+.22,y:4.05,w:2.05,h:1.05,fontSize:13,color:i===3?'C8D5D0':C.muted,margin:0});if(i<3)s.addText('→',{x:x+2.62,y:3.42,w:.32,h:.4,fontSize:21,bold:true,color:C.green,align:'center'});});footer(s,3);
s=base('The phrase is a key and a private map.','Receiver discovery');s.addText('PBKDF2',{x:.82,y:2.1,w:2.4,h:.45,fontSize:26,bold:true,color:C.green});s.addText('Shared phrase + random salt',{x:.82,y:2.7,w:3.2,h:.35,fontSize:15,color:C.muted});s.addText('AES KEY',{x:4.55,y:2.1,w:2.2,h:.45,fontSize:26,bold:true,color:C.ink});s.addText('Only the receiver can decrypt',{x:4.55,y:2.7,w:3.1,h:.35,fontSize:15,color:C.muted});s.addText('ROUTING TAGS',{x:8.15,y:2.1,w:3.7,h:.45,fontSize:26,bold:true,color:C.ink});s.addText('Rotate by time window; no stable identity',{x:8.15,y:2.7,w:4.1,h:.55,fontSize:15,color:C.muted});s.addText('→',{x:3.7,y:2.2,w:.45,h:.4,fontSize:28,color:C.lime,bold:true});s.addText('→',{x:7.3,y:2.2,w:.45,h:.4,fontSize:28,color:C.lime,bold:true});s.addShape(pptx.ShapeType.roundRect,{x:.8,y:4.1,w:11.7,h:1.45,fill:{color:C.ink},line:{color:C.ink}});s.addText('Relays can match temporary hints. They cannot derive plaintext, the full bundle, or a permanent receiver address.',{x:1.25,y:4.55,w:10.8,h:.55,fontSize:20,bold:true,color:C.white,align:'center',margin:0});footer(s,4);
s=base('RelayCoin pays for delivery, not noise.','Web3 incentive');const flow=[['Sender','Escrows RLY'],['Relay nodes','Carry fragments'],['Receiver','Signs receipt'],['Contract','Releases RLY']];flow.forEach((p,i)=>{const x=.72+i*3.12;s.addShape(pptx.ShapeType.ellipse,{x:x+.78,y:2.1,w:1.05,h:1.05,fill:{color:i===3?C.lime:C.ink},line:{color:i===3?C.lime:C.ink}});s.addText(i===0?'S':i===1?'R':i===2?'✓':'RLY',{x:x+.8,y:2.43,w:1.02,h:.25,fontSize:14,bold:true,color:i===3?C.ink:C.white,align:'center',margin:0});s.addText(p[0],{x:x+.48,y:3.42,w:1.65,h:.3,fontSize:17,bold:true,color:C.ink,align:'center'});s.addText(p[1],{x:x+.35,y:3.86,w:1.92,h:.3,fontSize:13,color:C.muted,align:'center'});if(i<3)s.addText('→',{x:x+2.55,y:2.43,w:.55,h:.3,fontSize:23,bold:true,color:C.green,align:'center'});});s.addText('No delivery, no reward. Sender-funded escrow and receipt-based settlement make spam expensive and useful carrying valuable.',{x:1.35,y:5.25,w:10.6,h:.85,fontSize:20,bold:true,color:C.green,align:'center',margin:0});footer(s,5);
s=base('A working cryptographic MVP today.','Live demo');s.addImage({path:screen,x:.72,y:1.86,w:7.45,h:4.95,sizing:'contain'});s.addText('What runs now',{x:8.7,y:1.95,w:3.2,h:.35,fontSize:20,bold:true,color:C.ink});const bullets=['PBKDF2 phrase-derived key','AES-256-GCM encryption','Five shuffled ciphertext fragments','Independent relay animation','SHA-256 integrity check','Wrong-phrase + tamper rejection','RLY reward settlement simulation'];s.addText(bullets.map(t=>({text:t,options:{bullet:{indent:14},hanging:3}})),{x:8.68,y:2.55,w:3.75,h:3.25,fontSize:15,color:C.muted,breakLine:true,paraSpaceAfterPt:10,margin:0});footer(s,6);
s=base('The protocol travels farther than the internet.','Roadmap');const roads=[['NOW','Browser MVP','Crypto core + Solidity reward contracts'],['NEXT','Real mesh','libp2p, Bluetooth, Wi-Fi Direct'],['FIELD','Remote range','LoRa bridge + erasure coding'],['SCALE','Open network','Testnet incentives + audited clients']];roads.forEach((p,i)=>{const x=.75+i*3.03;s.addText(p[0],{x,y:2.05,w:2.6,h:.22,fontSize:9,bold:true,color:C.green,charSpacing:2,align:'center'});s.addShape(pptx.ShapeType.roundRect,{x,y:2.55,w:2.62,h:2.65,fill:{color:i===0?C.ink:C.white},line:{color:i===0?C.ink:C.line}});s.addText(p[1],{x:x+.25,y:3.02,w:2.1,h:.45,fontSize:19,bold:true,color:i===0?C.lime:C.ink,align:'center'});s.addText(p[2],{x:x+.25,y:3.78,w:2.1,h:.7,fontSize:13,color:i===0?'C6D2CE':C.muted,align:'center',margin:0});if(i<3)s.addText('→',{x:x+2.68,y:3.48,w:.25,h:.35,fontSize:20,bold:true,color:C.green});});s.addText('RelayMesh turns disconnected devices into a privacy-preserving delivery network — and makes successful delivery worth something.',{x:1.35,y:5.85,w:10.65,h:.72,fontSize:21,bold:true,color:C.green,align:'center',margin:0});footer(s,7);
pptx.writeFile({fileName:'RelayMesh-Pitch-Deck.pptx'});
